services:
  kdc:
    build:
      context: ./kdc
    image: bde2020/hadoop-kdc:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    hostname: kdc.hadoop.lab
    volumes:
      - kerberos_secrets:/etc/security/keytabs
      - ./kerberos/krb5.conf:/etc/krb5.conf:ro
      - ./kerberos/kdc.conf:/etc/krb5kdc/kdc.conf:ro
      - ./kerberos/kadm5.acl:/etc/krb5kdc/kadm5.acl:ro
    environment:
      REALM: HADOOP.LAB
      KDC_HOST: kdc.hadoop.lab
      KDC_DB_PASSWORD: masterpw
      KADMIN_PRINCIPAL: admin/admin@HADOOP.LAB
      KADMIN_PASSWORD: adminpw
      LONGHD_PASSWORD: Hehehe123!@#
      KIDO_PASSWORD: Hehehe123!@#

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    hostname: namenode.hadoop.lab
    volumes:
      - namenode:/hadoop/dfs/name
      - kerberos_secrets:/etc/security/keytabs:ro
      - ./kerberos/krb5.conf:/etc/krb5.conf:ro
    environment:
      - CLUSTER_NAME=test
      - SERVICE_PRECONDITION=kdc:88
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: 9870

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    hostname: datanode.hadoop.lab
    volumes:
      - datanode:/hadoop/dfs/data
      - kerberos_secrets:/etc/security/keytabs:ro
      - ./kerberos/krb5.conf:/etc/krb5.conf:ro
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "kdc:88 namenode:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 9864

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    hostname: resourcemanager.hadoop.lab
    volumes:
      - kerberos_secrets:/etc/security/keytabs:ro
      - ./kerberos/krb5.conf:/etc/krb5.conf:ro
    environment:
      SERVICE_PRECONDITION: "kdc:88 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: 8088
    healthcheck:
      disable: true

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    hostname: nodemanager.hadoop.lab
    volumes:
      - kerberos_secrets:/etc/security/keytabs:ro
      - ./kerberos/krb5.conf:/etc/krb5.conf:ro
    environment:
      SERVICE_PRECONDITION: "kdc:88 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 8042

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    hostname: historyserver.hadoop.lab
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - kerberos_secrets:/etc/security/keytabs:ro
      - ./kerberos/krb5.conf:/etc/krb5.conf:ro
    environment:
      SERVICE_PRECONDITION: "kdc:88 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: 8188

volumes:
  datanode:
  namenode:
  hadoop_historyserver:
  kerberos_secrets:

networks:
  hbase:
    external:
      name: hbase
