services:
  namenode:
    environment:
      CORE_CONF_hadoop_http_filter_initializers: "org.apache.hadoop.security.HttpCrossOriginFilterInitializer"
      CORE_CONF_hadoop_http_cross___origin_enabled: "true"
      CORE_CONF_hadoop_http_cross___origin_allowed___origins: "http://10.10.10.156:9870"
      CORE_CONF_hadoop_http_cross___origin_allowed___methods: "GET,POST,PUT,DELETE,HEAD,OPTIONS"
      CORE_CONF_hadoop_http_cross___origin_allowed___headers: "X-Requested-With,Content-Type,Accept,Origin"
      CORE_CONF_hadoop_http_cross___origin_max___age: "1800"
      HDFS_CONF_dfs_client_use_datanode_hostname: "true"

  datanode:
    ports:
      - "9864:9864"
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_hadoop_http_filter_initializers: "org.apache.hadoop.security.HttpCrossOriginFilterInitializer"
      CORE_CONF_hadoop_http_cross___origin_enabled: "true"
      CORE_CONF_hadoop_http_cross___origin_allowed___origins: "http://10.10.10.156:9870"
      CORE_CONF_hadoop_http_cross___origin_allowed___methods: "GET,POST,PUT,DELETE,HEAD,OPTIONS"
      CORE_CONF_hadoop_http_cross___origin_allowed___headers: "X-Requested-With,Content-Type,Accept,Origin"
      CORE_CONF_hadoop_http_cross___origin_max___age: "1800"
      HDFS_CONF_dfs_client_use_datanode_hostname: "true"
      HDFS_CONF_dfs_datanode_use_datanode_hostname: "true"
      HDFS_CONF_dfs_datanode_hostname: "10.10.10.156"

  resourcemanager:
    ports:
      - "8088:8088"

  nodemanager1:
    ports:
      - "8042:8042"

  historyserver:
    ports:
      - "8188:8188"
